# Service - LoadBalancer
# # pb-service -lb.yml
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: kube-system
  labels:
    app: petclinic-app
spec:
  selector:
    app: petclinic-app
  type: NodePort
  ports:
  - nodePort: 32759
    port: 8080
    targetPort: 8080




